name: dcx lint, build, build tests

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install -r --frozen-lockfile
  lint:
      - name: Run linter for all packages
        run: pnpm lint
  build:
      - name: Build all packages
        run: pnpm build
  build-tests:
      - name: Build all tests
        run: pnpm build:tests:node
      
      # - name: Run all tests
      #   run: pnpm test:node
      
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4.0.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: TBD54566975/incubation-dcx